name: Network Tests

# Only run on branches (e.g. not tags)
on:
  workflow_dispatch:
  push:

jobs:
  fio:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-osu-selfhosted, ubuntu-22.04-ppc64le]

    steps:
        
      - name: Download Tests from speedtest.tele2.net
        run: |
          time curl -o file.zip http://speedtest.tele2.net/1GB.zi

      - name: Download Tests from 212.183.159.230
        run: |
          time curl -o file.zip http://212.183.159.230/1GB.zip
