name: Speed Test

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: Speed Test - ${{ matrix.os }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            runner_owner: "github-hosted"
            runner_files: "/home/runner/runners/2.321.0/_diag/Runner_*"
            worker_files: "/home/runner/runners/2.321.0/_diag/Worker_*"
          # - os: ubuntu-22.04-osu-selfhosted
          #   runner_owner: "actions-runner-ppc64le"
          #   runner_files: "/opt/runner/_diag/Runner_*"
          #   worker_files: "/opt/runner/_diag/Worker_*"
          - os: ubuntu-24.04-ppc64le
            runner_owner: "actions-runner-ppc64le"
            runner_files: "/opt/runner/_diag/Runner_*"
            worker_files: "/opt/runner/_diag/Worker_*"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Speed test
        run: |
          curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python3 -
